apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvmf-tgt
  namespace: obnvmf
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: nvmf-tgt
      role: node
  template:
    metadata:
      labels:
        app: nvmf-tgt
        role: node
    spec:
      priorityClassName: system-node-critical
      serviceAccount: obnvmf-admin
      hostNetwork: true
      securityContext: {}
      containers:
        - name: nvmf-tgt
          securityContext:
            privileged: true
          image: simonc.azurecr.io/liteio/nvmf-tgt:latest
          command:
          - /usr/bin/nvmf_tgt
          args:
            - "-m"
            - "[1]"
            - "-s" #memory size in MB for DPDK
            - "1024"
            - "--num-trace-entries"
            - "0"
            - "-L"
            - "bdev"
            - "-L"
            - "lvol"
            - "-L"
            - "rpc"
            - "-L"
            - "nvmf"
          resources:
            requests:
              cpu: "2"
              memory: "2Gi"
              hugepages-2Mi: "2Gi"
            limits:
              cpu: "2"
              memory: "2Gi"
              hugepages-2Mi: "2Gi"
          volumeMounts:
            - name: hugepage
              mountPath: /hugepages
            - name: device
              mountPath: /dev
            - name: dshm
              mountPath: /dev/shm
            - name: sock-dir
              mountPath: /var/tmp
            - name: data-dir
              mountPath: /local-storage
      volumes:
        - name: hugepage
          emptyDir:
            medium: HugePages
        - name: device
          hostPath:
            path: /dev
            type: Directory
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
        - name: sock-dir
          hostPath:
            path: /usr/tmp/spdk
            type: DirectoryOrCreate
        - name: data-dir
          hostPath:
            path: /local-storage
            type: DirectoryOrCreate
