kind: Deployment
apiVersion: apps/v1
metadata:
  name: csi-antstor-controller
  namespace: obnvmf
  labels:
    component: csi-antstor-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      component: csi-antstor-controller
  template:
    metadata:
      labels:
        component: csi-antstor-controller
    spec:
      serviceAccount: obnvmf-admin
      containers:
      - name: csi-antstor
        image: simonc.azurecr.io/liteio/node-disk-controller:test
        imagePullPolicy: Always

        command:
        - /node-disk-controller
        args:
        - antstor
        - "server"
        - "--driver=antstor.csi.alipay.com"
        - "--endpoint=$(CSI_ENDPOINT)"
        - "--maxVolume=20"
        - "--nodeID=$(NODE_ID)"
        - "--logtostderr"
        - "--initKernelMod=false"
        - "--isController=true"
        env:
        - name: NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: CSI_ENDPOINT
          value: unix://csi/csi.sock
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "100m"
            memory: "100Mi"
        volumeMounts:
        - name: socket-dir
          mountPath: /csi
      - name: csi-provisioner
        image: "mcr.microsoft.com/oss/kubernetes-csi/csi-provisioner:v2.1.1"
        args:
            #- "--provisioner=antstor.csi.alipay.com"
            - "--csi-address=$(ADDRESS)"
            - "--extra-create-metadata=true"
            - "--v=5"
            - "--feature-gates=Topology=true"
        env:
        - name: ADDRESS
          value: /csi/csi.sock
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "100m"
            memory: "100Mi"
        imagePullPolicy: "IfNotPresent"
        volumeMounts:
        - name: socket-dir
          mountPath: /csi
      - name: csi-attacher
        image: mcr.microsoft.com/oss/kubernetes-csi/csi-attacher:v2.0.0
        args:
        - "--csi-address=$(ADDRESS)"
        - "--v=5"
        env:
        - name: ADDRESS
          value: /csi/csi.sock
        - name: MY_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          limits:
            cpu: "1"
            memory: "500Mi"
          requests:
            cpu: "0"
            memory: "0Mi"
        imagePullPolicy: "IfNotPresent"
        volumeMounts:
        - name: socket-dir
          mountPath: /csi
      # - name: csi-resizer
      #   image: mcr.microsoft.com/oss/kubernetes-csi/csi-resizer:v1.3.0
      #   args:
      #     - "--v=5"
      #     - "--csi-address=$(CSI_ENDPOINT)"
      #     #- "--leader-election"
      #   env:
      #     - name: CSI_ENDPOINT
      #       value: /socketDir/csi.sock
      #   volumeMounts:
      #     - name: socket-dir
      #       mountPath: /socketDir/
      #   resources:
      #     limits:
      #       cpu: "2"
      #       memory: "4Gi"
      #     requests:
      #       cpu: "1"
      #       memory: "2Gi"
      - name: liveness-probe
        image: mcr.microsoft.com/oss/kubernetes-csi/livenessprobe:v2.0.0
        args:
        - "--csi-address=/csi/csi.sock"
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0"
            memory: "0Gi"
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
      volumes:
      - name: socket-dir
        emptyDir: {}